import './globals.css'
import { Inter } from 'next/font/google'
import TopNavBar from '../components/TopNavBar'
import NextAuthProvider from '../components/SessionProvider'
import CategoryPills from '../components/CategoryPills'
import SideBar from '../components/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'YouTube Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='max-h-screen flex flex-col'>
        <NextAuthProvider>
          <TopNavBar />

          <div className='grid grid-cols-[auto,1fr] flex-grow-1 overflow-auto'>
            <SideBar />

            <div className='overflow-x-hidden px-4 pb-4 '>
              <div className='sticky top-0 z-10 pb-4 bg-white'>
                <CategoryPills/>
              </div>

              <div className='h-max grid grid-cols-[repeat(auto-fill,minmax(300px,1fr))] gap-5 p-6'>
                {children}
              </div>
            </div>

          </div>
        </NextAuthProvider>
      </body>
    </html>
  )
}
